### ISSUE TITLE
[BUG] - Table: minWidth and other column props not recognized

### ISSUE THREAD

**Issue by stx-chris** [heroui-inc/heroui#1667]
### NextUI Version

2.1.13

### Describe the bug

Some of the column properties, e.g. `minWidth`, are not applied

### Steps to Reproduce the Bug or Issue

Apply any value for `minWidth`

### Expected behavior

Property should be applied to styles

### Operating System Version

macOS

### Browser

Chrome

**Comment by EtherealData** [comment]
align doesn't work either. Can you add that detail to this bug? 🙏

**Comment by LagoonProject** [comment]
TableColumn properties (align, width, maxWidth...) are not working here neither.

Version:

```
"@nextui-org/react": "^2.2.9",
"next": "14.0.4",
```

**Comment by duchoan6814** [comment]
> TableColumn properties (align, width, maxWidth...) are not working here neither.
> 
> Version:
> 
> ```
> "@nextui-org/react": "^2.2.9",
> "next": "14.0.4",
> ```

.

**Comment by captainkapnap** [comment]
> TableColumn properties (align, width, maxWidth...) are not working here neither.
> 
> Version:
> 
> ```
> "@nextui-org/react": "^2.2.9",
> "next": "14.0.4",
> ```

`    "next": "^14.1.0",
    "@nextui-org/react": "^2.2.9",`

Same here.  Work-arounding it by adding length to the column header name for now.

**Comment by kasulk** [comment]
Same here, doesn't even work in the examples in the docs:

![code](https://github.com/nextui-org/nextui/assets/113789376/c76b9105-1b02-4a3f-bf8f-2e14e71c05cc)
![ui](https://github.com/nextui-org/nextui/assets/113789376/0a22a91c-4cff-44a6-a378-d9d07a764feb)

**Comment by happydayxxl** [comment]
any news on this?

**Comment by THE-SIMPLE-MARK** [comment]
I am having the same issue here. Are there any temporary workarounds available? I need to set the width of my column.

**Comment by happydayxxl** [comment]
> I am having the same issue here. Are there any temporary workarounds available? I need to set the width and alignment of my column.

i have solved it with <TableColumn className='min-w-48'>.... i am using tailwind

**Comment by ygd** [comment]
I am using tailwind as well and solved the alignment issue with the className "text-right"

**Comment by PabloOliveiraSantos** [comment]
Any news about this issue?

**Comment by matteogilioli** [comment]
Any updates?

**Comment by LeoLin4258** [comment]
You can try adding an element inside <TableColumn> and apply your desired styles to that element. This approach might achieve a similar effect.

``` js
<TableColumn ><div className="border border-dashed w-80">Name</div></TableColumn>
```

**Comment by Ribosom** [comment]
I am new to next-ui, even an autogenerated project via nextui init does not work properly.
`maxWidth `and `justify` don't work in the Navbar of the autogenerated project. 

Version: NextUI CLI v0.3.4

**Comment by rayaqin** [comment]
> I am using tailwind as well and solved the alignment issue with the className "text-right"



> > I am having the same issue here. Are there any temporary workarounds available? I need to set the width and alignment of my column.
> 
> i have solved it with `<TableColumn className='min-w-48'>` .... i am using tailwind

Of course you can solve it with tailwind. You can also solve it with css.
You could just not use nextui at all and do everything on your own. But the point is that the nextui functionality that should work does not work, and should be fixed.
Getting the solution that worked for you out is a good thing regardless, I'm not trying to be toxic here, but this is still an issue with nexui that needs to be dealt with.

**Comment by awestm** [comment]
Still not fixed as of March 2025, 18 months since first reported...

**Comment by THE-SIMPLE-MARK** [comment]
I can confirm that this is still an issue. I personally don't like how the columns grow to attempt to fill the available space. More often than not, they grow where they don't need to and vice versa.

A temporary solution, as others have mentioned, is to put your styles on a wrapper div inside `TabelColumn`. You can then apply any width restrictions and it works as expected.

**Comment by DirkOdendaal** [comment]
Widths and props are working just fine.

Here is a screenshot;

Actions clearly centered.
<img width="1254" height="183" alt="Image" src="https://github.com/user-attachments/assets/73c9de7d-19f5-465f-bfff-7cb606d1850e" />

And column widths apply correctly.
<img width="902" height="579" alt="Image" src="https://github.com/user-attachments/assets/b98d4377-1f41-4a81-95af-d7b9a1f3bf08" />


Code snippet of table:
```
<Table
					removeWrapper
					aria-label="Recent activity table"
					classNames={{
						base: "h-full max-h-full overflow-auto px-1",
						th: "sticky top-0 z-20 bakcrop-opacity-0",
					}}
				>
					<TableHeader>
						<TableColumn>Job title</TableColumn>
						<TableColumn>Company</TableColumn>
						<TableColumn>Created at</TableColumn>
						<TableColumn align="center" width={70}>
							Actions
						</TableColumn>
					</TableHeader>
					<TableBody>
						{jobs.map((job) => (
							<TableRow key={job.id}>
								<TableCell>{job.title}</TableCell>
								<TableCell>{job.companyName}</TableCell>
								<TableCell>{job.createdAt.toLocaleString()}</TableCell>
								<TableCell>
									<Dropdown>
										<DropdownTrigger>
											<Button isIconOnly className="rotate-90" size="sm" variant="light">
												<Icon icon="solar:menu-dots-bold" />
											</Button>
										</DropdownTrigger>
										<DropdownMenu>
											<DropdownItem key="delete" onPress={() => handleDeleteJob(job.id)}>
												Delete
											</DropdownItem>
										</DropdownMenu>
									</Dropdown>
								</TableCell>
							</TableRow>
						))}
					</TableBody>
				</Table>
```
Versions:
```
    "@heroui/button": "2.2.22",
    "@heroui/code": "2.2.16",
    "@heroui/input": "2.4.22",
    "@heroui/kbd": "2.2.17",
    "@heroui/link": "2.2.19",
    "@heroui/listbox": "2.3.21",
    "@heroui/navbar": "2.2.20",
    "@heroui/react": "^2.7.11",
    "@heroui/snippet": "2.2.23",
    "@heroui/switch": "2.2.20",
    "@heroui/system": "2.4.18",
    "@heroui/theme": "2.4.17",
```

I'd recommend closing the issue.
