### ISSUE TITLE
[BUG] - Checkbox onValueChange is fired twice on mobile

### ISSUE THREAD

**Issue by Foxhunt** [heroui-inc/heroui#5158]
### HeroUI Version

2.7.5

### Describe the bug

The `onValueChange` eventhandler of the `Checkbox`-Component is fired twice on mobile.
Once with the changes value and a second time with the previous value.

### Your Example Website or App

https://www.heroui.com/docs/components/checkbox#controlled

### Steps to Reproduce the Bug or Issue

1. open https://www.heroui.com/docs/components/checkbox#controlled in chrome
2. open dev tools
3. enable device toolbar
4. set dimensions to responsive
5. set device type to mobile
6. click/tab the checkbox

### Expected behavior

The `onValueChange` eventhandler of the `Checkbox`-Component should only be fired once.

### Operating System Version

macOS

### Browser

Chrome

**Comment by nextrie** [comment]
+1

**Comment by cnakarimi** [comment]
when will they solve this issue?

**Comment by erwin-huang** [comment]
> when will they solve this issue?

@cnakarimi It should have been fixed in version 2.7.9. 

**Release Tag**: https://github.com/heroui-inc/heroui/releases/tag/%40heroui%2Freact%402.7.9
• chore(docs): add missing onValueChange in CheckboxGroup by [@wingkwong](https://github.com/wingkwong) in https://github.com/heroui-inc/heroui/pull/5332

**Comment by wingkwong** [comment]
@erwin-huang The PR you linked was simply updating docs. I think It has nothing to do with the issue. Need to revisit this issue again with the latest version.

**Comment by wingkwong** [comment]
anyone could still reproduce the issue? I tried with chrome on latest docs and seems looks fine.

**Comment by erwin-huang** [comment]
It worked fine on my project as well (version 2.7.9)

**Comment by cnakarimi** [comment]
I am using tailwind v-4 so I have         "@heroui/react": "^2.8.0-beta.4",
 is it fixed in this version too?

**Comment by wingkwong** [comment]
Closing in favor of v3. If the issue is reproducible in v3, please create a new one with a minimal reproducible example.
