### ISSUE TITLE
[BUG] - HeroUI routing not working with Tanstack Router

### ISSUE THREAD

**Issue by sai-poona** [heroui-inc/heroui#5463]
### HeroUI Version

2.8.0-beta.13

### Describe the bug

Hi,

I'm currently in the process of building a new application and I'm using React(Vite) + HeroUI + Tanstack. Following the HeroUI's documentation around integrating routing, I have noticed that the routing in HeroUI is not working with Tanstack router. 

The code over here throws a typescript error "Spread types may only be created from object types.", instead of picking up the config from the RouterConfig in the declared module (as shown in the docs). 

`<HeroUIProvider
      navigate={(to, options) => router.navigate({to, ...options})}
      useHref={(to) => router.buildLocation({to}).href}
    >`

When providing a value to a HeroUI component like Link, typescript shows the allowed href values which maps to the available routes in the router but when clicking on the links, it behaves like a normal href link instead of leveraging the router.navigate.

Unable to create a sandbox but here is a test repo which can be used to reproduce the issue: https://github.com/sai-poona/heroui-tanstack-test

### Your Example Website or App

https://github.com/sai-poona/heroui-tanstack-test

### Steps to Reproduce the Bug or Issue

Steps to reproduce:
1. Clone the repo
2. `cd heroui-tanstack-test/`
3. `npm install`
4. `npm run dev`

Once you open the app in the browser, you should see 2 sections, one with the Tanstack Router Link which works as expected and another with HeroUI Link which does not leverage the router

### Expected behavior

When clicking on a HeroUI link, it should leverage the router to navigate to pages instead of loading them like href links

### Screenshots or Videos

https://github.com/user-attachments/assets/4a3695b7-b433-477d-9324-e878a7fce83d

### Operating System Version

macOS

### Browser

Chrome

**Comment by liu245933567** [comment]
I am also waiting for this issue to be resolved

**Comment by ttessarolo** [comment]
Me to 😟

**Comment by wingkwong** [comment]
Fixed in [2.8.0-beta.15](https://www.npmjs.com/package/@heroui/react/v/2.8.0-beta.15)

**Comment by ttessarolo** [comment]
@wingkwong still have the same problem on 2.8.1
the fix is still to be merged?

**Comment by wingkwong** [comment]
@ttessarolo it should be included in latest. please share your repo or sandbox.

**Comment by ttessarolo** [comment]
Trust me It doesn't work:

My packages:

```jason
   "@tanstack/react-router": "^1.129.7",
    "@tanstack/react-router-devtools": "^1.129.7",
    "@tanstack/react-router-with-query": "^1.129.7",
    "@tanstack/react-start": "^1.129.7",
    "@heroui/react": "^2.8.1",
    "@heroui/system": "^2.4.19",
    "@heroui/theme": "^2.4.19",
```

HeroUIProvider configuration:

```javascript

function RootDocument({ children }: { children: React.ReactNode }) {
  let router = useRouter();

  return (
    <html lang={getLocale()} className="dark text-foreground  bg-slate-950">
      <head>
        <HeadContent />
      </head>
      <body className="">
        <HeroUIProvider
          navigate={(to, options) =>
            router.navigate({ to, ...(options ?? {}) })
          }
          useHref={(to) => router.buildLocation({ to }).href}
        >
          <ToastProvider />
          {children}
          <TanStackRouterDevtools position="bottom-right" />
          <ReactQueryDevtools buttonPosition="bottom-left" />
          <Scripts />
        </HeroUIProvider>
      </body>
    </html>
  );
}
```

Then my navigation is a simple TabBar:

```javascript
export const TabBar = () => {
  const location = useLocation();

  return (
    <Tabs
      size="lg"
      variant="light"
      radius="full"
      disabledKeys={["profile"]}
      selectedKey={location.pathname.split("/")[1]}
    >
      <Tab key="" title="Home" className="bg-white/0" href="/" />
      <Tab key="kitchen" title="kitchen" href="/kitchen/owner" />
      <Tab key="explore" title="explore"  href="/explore" />
      <Tab
        key="profile"
        className="bg-white/0 data-[disabled=true]:opacity-100 backdrop-blur-lg shadow-none"
        title="Profile"
      />
    </Tabs>
  );
};
```

I need to use ``selectedKey={location.pathname.split("/")[1]}`` to change the current Tab accordingly.

Then on every click on a Tab I have a full page reload.

**Comment by wingkwong** [comment]
@ttessarolo You either need `@heroui/react` (global package) or `@heroui/system` + `@heroui/theme` (individual package) but not all three at the same time. You may try remove the extra package(s) and try again. If it still fails, please share a repo link or a minimal reproducible sandbox instead so that I could directly debug on it. Thanks.

```
"@heroui/react": "^2.8.1",
"@heroui/system": "^2.4.19",
"@heroui/theme": "^2.4.19",
```

**Comment by wingkwong** [comment]
@ttessarolo Just an update. It seems RA team has recently upgraded the packages. We'll release a patch version in the coming days. It should resolve the issue.

**Comment by ttessarolo** [comment]
@wingkwong OK great, thank you very much. For now I've switched to TanStack Router <Link>

**Comment by wingkwong** [comment]
@ttessarolo PR is created. Alternatively you may use the PR build version. We may release the patch version tomorrow.

```
npm i https://pkg.pr.new/@heroui/react@5517
```

**Comment by kisonay** [comment]
I see this too, previously I had resolved `@react-aria/utils` to version 3.28.1. What version should be resolved here?

**Comment by wingkwong** [comment]
@kisonay now they bumped the version to `3.30.0` or use the PR build `https://pkg.pr.new/@heroui/react@5517`. however, it seems that the setup is different in new version. may check out the doc part.
